<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>SeroGlint.DotNet.Notifications</Title>
    <Description>A library built using SeroGlint.DotNet.Common and ~.Logging that adds wrapping for easier use of operating system toast notifications</Description>
    <Copyright>Iterix 2025</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SeroGlint.DotNet.Logging\SeroGlint.DotNet.Logging.csproj" />
    <ProjectReference Include="..\SeroGlint.DotNet\SeroGlint.DotNet.Common.csproj" />
  </ItemGroup>

</Project>
