<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>SeroGlint.DotNet.Ipc</Title>
    <Description>A library built using SeroGlint.DotNet.Common, ~.Logging, and ~.Security that makes it easier to build and use named pipes</Description>
    <Copyright>Iterix 2025</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SeroGlint.DotNet.Logging\SeroGlint.DotNet.Logging.csproj" />
    <ProjectReference Include="..\SeroGlint.DotNet.Security\SeroGlint.DotNet.Security.csproj" />
    <ProjectReference Include="..\SeroGlint.DotNet\SeroGlint.DotNet.Common.csproj" />
  </ItemGroup>

</Project>
